# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [28]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [29]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
data_path = Path("./Resources/applicants_data.csv")
applicant_data_df = pd.read_csv(data_path, infer_datetime_format=True, parse_dates=True)

# Review the DataFrame
applicant_data_df

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...,...
34294,996009318,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,996010315,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,996012607,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,996015768,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,996086871,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [30]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [31]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(['EIN','NAME'], axis=1)

# Review the DataFrame
applicant_data_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [32]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [33]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [34]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [35]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names(categorical_variables)
)

# Review the DataFrame
encoded_df

C:\Users\Nia\anaconda3\envs\FinTech\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [36]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([applicant_data_df.drop(columns=categorical_variables),encoded_df], axis=1)

# Review the Dataframe
encoded_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [37]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL']

# Display a sample of y
y.tail()

34294    0
34295    0
34296    0
34297    1
34298    0
Name: IS_SUCCESSFUL, dtype: int64

In [38]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(['IS_SUCCESSFUL'], axis=1)

# Review the features DataFrame
X

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [39]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [40]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [54]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.columns)

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [42]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  number_input_features * 2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

232

In [43]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (number_input_features * 2) + 1

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

233

In [44]:
# Create the Sequential model instance
nn = Sequential()

In [45]:
# Add the first hidden layer
nn.add(
    Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

In [46]:
# Add the second hidden layer
nn.add(
    Dense(units=hidden_nodes_layer2, activation="relu")
)

In [47]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons, activation="linear"))

In [48]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 232)               27144

 dense_1 (Dense)             (None, 233)               54289

 dense_2 (Dense)             (None, 1)                 234

=================================================================
Total params: 81,667
Trainable params: 81,667
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [49]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [50]:
# Fit the model using 50 epochs and the training data
nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 1ms/step - loss: 1.8279 - accuracy: 0.6689
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 1.2320 - accuracy: 0.6908
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 0.9023 - accuracy: 0.7210
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8476 - accuracy: 0.7212
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8220 - accuracy: 0.7206
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8457 - accuracy: 0.7168
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8128 - accuracy: 0.7149
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8521 - accuracy: 0.7037
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7419 - accuracy: 0.7216
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 0.6986 - accuracy: 0.7250
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 0.7534 - accuracy: 0.7148
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 0.8594 - accuracy: 0.7135
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.8984 - accuracy: 0.7119
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.8713 - accuracy: 0.7152
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.8530 - accuracy: 0.7212
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.8243 - accuracy: 0.7228
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7157 - accuracy: 0.7287
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7190 - accuracy: 0.7269
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7190 - accuracy: 0.7270
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7404 - accuracy: 0.7260
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7616 - accuracy: 0.7212
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7262 - accuracy: 0.7289
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7379 - accuracy: 0.7233
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7030 - accuracy: 0.7288
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6838 - accuracy: 0.7305
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6962 - accuracy: 0.7231
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7058 - accuracy: 0.7317
Epoch 28/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6977 - accuracy: 0.7329
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7120 - accuracy: 0.7234
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7249 - accuracy: 0.7284
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7315 - accuracy: 0.7288
Epoch 32/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7058 - accuracy: 0.7335
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6875 - accuracy: 0.7303
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6753 - accuracy: 0.7337
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6789 - accuracy: 0.7320
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6648 - accuracy: 0.7233
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6596 - accuracy: 0.7343
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6627 - accuracy: 0.7321
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6748 - accuracy: 0.7323
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6836 - accuracy: 0.7336
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6854 - accuracy: 0.7342
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6867 - accuracy: 0.7210
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6887 - accuracy: 0.7357
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6823 - accuracy: 0.7329
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7242 - accuracy: 0.7168
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.8974 - accuracy: 0.7200
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.9245 - accuracy: 0.7099
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.9406 - accuracy: 0.7165
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.7469 - accuracy: 0.7322
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7479 - accuracy: 0.7315

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [51]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.7650 - accuracy: 0.7254 - 387ms/epoch - 1ms/step
Loss: 0.7649664878845215, Accuracy: 0.7253644466400146

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [53]:
# Set the model's file path
file_path = Path("./Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [55]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [56]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [57]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = number_input_features * 3

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

348

In [58]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [59]:
# First hidden layer
nn_A1.add(
    Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu")
)


# Output layer
nn_A1.add(Dense(units=number_output_neurons_A1, activation="linear"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 348)               40716

 dense_4 (Dense)             (None, 1)                 349

=================================================================
Total params: 41,065
Trainable params: 41,065
Non-trainable params: 0
_________________________________________________________________

In [60]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [61]:
# Fit the model using 200 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train , epochs=200)

Epoch 1/200
804/804 [==============================] - 3s 1ms/step - loss: 2.1887 - accuracy: 0.6494
Epoch 2/200
804/804 [==============================] - 1s 1ms/step - loss: 3.5200 - accuracy: 0.6225
Epoch 3/200
804/804 [==============================] - 1s 1ms/step - loss: 3.4327 - accuracy: 0.6519
Epoch 4/200
804/804 [==============================] - 1s 1ms/step - loss: 3.4351 - accuracy: 0.6609
Epoch 5/200
804/804 [==============================] - 1s 1ms/step - loss: 3.5074 - accuracy: 0.6723
Epoch 6/200
804/804 [==============================] - 1s 1ms/step - loss: 3.6687 - accuracy: 0.6850
Epoch 7/200
804/804 [==============================] - 1s 1ms/step - loss: 3.6753 - accuracy: 0.6751
Epoch 8/200
804/804 [==============================] - 1s 1ms/step - loss: 3.1654 - accuracy: 0.6897
Epoch 9/200
804/804 [==============================] - 1s 1ms/step - loss: 3.2675 - accuracy: 0.6884
Epoch 10/200
804/804 [==============================] - 1s 1ms/step - loss: 3.1394 - accuracy: 0.6957
Epoch 11/200
804/804 [==============================] - 1s 1ms/step - loss: 3.0037 - accuracy: 0.7087
Epoch 12/200
804/804 [==============================] - 1s 1ms/step - loss: 3.8859 - accuracy: 0.6787
Epoch 13/200
804/804 [==============================] - 1s 1ms/step - loss: 3.9995 - accuracy: 0.6781
Epoch 14/200
804/804 [==============================] - 1s 1ms/step - loss: 3.9541 - accuracy: 0.6763
Epoch 15/200
804/804 [==============================] - 1s 1ms/step - loss: 4.1132 - accuracy: 0.6677
Epoch 16/200
804/804 [==============================] - 1s 1ms/step - loss: 3.8333 - accuracy: 0.6755
Epoch 17/200
804/804 [==============================] - 1s 1ms/step - loss: 3.2349 - accuracy: 0.6987
Epoch 18/200
804/804 [==============================] - 1s 2ms/step - loss: 3.2364 - accuracy: 0.7022
Epoch 19/200
804/804 [==============================] - 1s 2ms/step - loss: 3.2536 - accuracy: 0.6975
Epoch 20/200
804/804 [==============================] - 1s 1ms/step - loss: 2.7188 - accuracy: 0.7157
Epoch 21/200
804/804 [==============================] - 1s 2ms/step - loss: 2.7339 - accuracy: 0.7157
Epoch 22/200
804/804 [==============================] - 1s 2ms/step - loss: 2.4526 - accuracy: 0.7084
Epoch 23/200
804/804 [==============================] - 1s 1ms/step - loss: 3.1838 - accuracy: 0.6674
Epoch 24/200
804/804 [==============================] - 1s 1ms/step - loss: 2.5475 - accuracy: 0.6643
Epoch 25/200
804/804 [==============================] - 1s 1ms/step - loss: 2.7837 - accuracy: 0.6367
Epoch 26/200
804/804 [==============================] - 1s 2ms/step - loss: 2.7056 - accuracy: 0.6298
Epoch 27/200
804/804 [==============================] - 1s 1ms/step - loss: 2.3854 - accuracy: 0.6499
Epoch 28/200
804/804 [==============================] - 1s 1ms/step - loss: 2.1448 - accuracy: 0.6906
Epoch 29/200
804/804 [==============================] - 1s 1ms/step - loss: 2.1334 - accuracy: 0.7227
Epoch 30/200
804/804 [==============================] - 1s 1ms/step - loss: 2.5785 - accuracy: 0.6951
Epoch 31/200
804/804 [==============================] - 1s 2ms/step - loss: 2.9786 - accuracy: 0.6950
Epoch 32/200
804/804 [==============================] - 1s 2ms/step - loss: 2.4104 - accuracy: 0.7137
Epoch 33/200
804/804 [==============================] - 1s 2ms/step - loss: 2.4113 - accuracy: 0.7176
Epoch 34/200
804/804 [==============================] - 1s 2ms/step - loss: 2.3185 - accuracy: 0.7203
Epoch 35/200
804/804 [==============================] - 1s 2ms/step - loss: 2.3595 - accuracy: 0.7184
Epoch 36/200
804/804 [==============================] - 1s 1ms/step - loss: 2.8817 - accuracy: 0.6787
Epoch 37/200
804/804 [==============================] - 1s 1ms/step - loss: 2.1585 - accuracy: 0.6813
Epoch 38/200
804/804 [==============================] - 1s 2ms/step - loss: 1.2847 - accuracy: 0.7215
Epoch 39/200
804/804 [==============================] - 1s 1ms/step - loss: 1.2201 - accuracy: 0.7208
Epoch 40/200
804/804 [==============================] - 1s 1ms/step - loss: 1.5170 - accuracy: 0.7040
Epoch 41/200
804/804 [==============================] - 1s 2ms/step - loss: 1.8634 - accuracy: 0.6786
Epoch 42/200
804/804 [==============================] - 1s 1ms/step - loss: 1.8685 - accuracy: 0.6822
Epoch 43/200
804/804 [==============================] - 1s 1ms/step - loss: 1.8621 - accuracy: 0.6837
Epoch 44/200
804/804 [==============================] - 1s 1ms/step - loss: 1.8990 - accuracy: 0.6765
Epoch 45/200
804/804 [==============================] - 1s 1ms/step - loss: 1.8784 - accuracy: 0.6822
Epoch 46/200
804/804 [==============================] - 1s 1ms/step - loss: 1.8069 - accuracy: 0.6845
Epoch 47/200
804/804 [==============================] - 1s 2ms/step - loss: 1.7910 - accuracy: 0.6842
Epoch 48/200
804/804 [==============================] - 2s 2ms/step - loss: 1.8244 - accuracy: 0.6798
Epoch 49/200
804/804 [==============================] - 2s 3ms/step - loss: 1.8396 - accuracy: 0.6759
Epoch 50/200
804/804 [==============================] - 1s 2ms/step - loss: 1.6995 - accuracy: 0.6902
Epoch 51/200
804/804 [==============================] - 1s 1ms/step - loss: 1.5690 - accuracy: 0.6982
Epoch 52/200
804/804 [==============================] - 1s 1ms/step - loss: 1.4316 - accuracy: 0.7081
Epoch 53/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3648 - accuracy: 0.7160
Epoch 54/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3281 - accuracy: 0.7154
Epoch 55/200
804/804 [==============================] - 1s 2ms/step - loss: 1.3508 - accuracy: 0.7159
Epoch 56/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3717 - accuracy: 0.7108
Epoch 57/200
804/804 [==============================] - 1s 1ms/step - loss: 1.6859 - accuracy: 0.6950
Epoch 58/200
804/804 [==============================] - 1s 1ms/step - loss: 1.5743 - accuracy: 0.6997
Epoch 59/200
804/804 [==============================] - 1s 1ms/step - loss: 1.4076 - accuracy: 0.6944
Epoch 60/200
804/804 [==============================] - 1s 2ms/step - loss: 1.5444 - accuracy: 0.7018
Epoch 61/200
804/804 [==============================] - 1s 2ms/step - loss: 1.5504 - accuracy: 0.7000
Epoch 62/200
804/804 [==============================] - 1s 1ms/step - loss: 1.6444 - accuracy: 0.6921
Epoch 63/200
804/804 [==============================] - 1s 2ms/step - loss: 1.5380 - accuracy: 0.6966
Epoch 64/200
804/804 [==============================] - 1s 2ms/step - loss: 1.8264 - accuracy: 0.6730
Epoch 65/200
804/804 [==============================] - 1s 1ms/step - loss: 1.8117 - accuracy: 0.6851
Epoch 66/200
804/804 [==============================] - 1s 2ms/step - loss: 1.5130 - accuracy: 0.7046
Epoch 67/200
804/804 [==============================] - 1s 2ms/step - loss: 1.3521 - accuracy: 0.7105
Epoch 68/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3334 - accuracy: 0.7179
Epoch 69/200
804/804 [==============================] - 1s 2ms/step - loss: 1.2833 - accuracy: 0.7186
Epoch 70/200
804/804 [==============================] - 1s 1ms/step - loss: 1.5547 - accuracy: 0.7038
Epoch 71/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3791 - accuracy: 0.7118
Epoch 72/200
804/804 [==============================] - 1s 2ms/step - loss: 1.2523 - accuracy: 0.7193
Epoch 73/200
804/804 [==============================] - 2s 2ms/step - loss: 1.2748 - accuracy: 0.7168
Epoch 74/200
804/804 [==============================] - 2s 2ms/step - loss: 1.4577 - accuracy: 0.7071
Epoch 75/200
804/804 [==============================] - 1s 2ms/step - loss: 1.2251 - accuracy: 0.7220
Epoch 76/200
804/804 [==============================] - 1s 1ms/step - loss: 1.2733 - accuracy: 0.7179
Epoch 77/200
804/804 [==============================] - 1s 1ms/step - loss: 1.2548 - accuracy: 0.7186
Epoch 78/200
804/804 [==============================] - 1s 1ms/step - loss: 1.5870 - accuracy: 0.7006
Epoch 79/200
804/804 [==============================] - 1s 1ms/step - loss: 1.9776 - accuracy: 0.6698
Epoch 80/200
804/804 [==============================] - 1s 1ms/step - loss: 2.1235 - accuracy: 0.6654
Epoch 81/200

804/804 [==============================] - 1s 1ms/step - loss: 1.9504 - accuracy: 0.6729
Epoch 82/200
804/804 [==============================] - 1s 1ms/step - loss: 1.5079 - accuracy: 0.6967
Epoch 83/200
804/804 [==============================] - 1s 1ms/step - loss: 1.4566 - accuracy: 0.7148
Epoch 84/200
804/804 [==============================] - 1s 1ms/step - loss: 1.4188 - accuracy: 0.7126
Epoch 85/200
804/804 [==============================] - 1s 1ms/step - loss: 1.6722 - accuracy: 0.6929
Epoch 86/200
804/804 [==============================] - 1s 2ms/step - loss: 1.3733 - accuracy: 0.7162
Epoch 87/200
804/804 [==============================] - 1s 2ms/step - loss: 1.3994 - accuracy: 0.7128
Epoch 88/200
804/804 [==============================] - 1s 1ms/step - loss: 1.2693 - accuracy: 0.7234
Epoch 89/200
804/804 [==============================] - 1s 1ms/step - loss: 1.2873 - accuracy: 0.7249
Epoch 90/200
804/804 [==============================] - 1s 1ms/step - loss: 1.2511 - accuracy: 0.7221
Epoch 91/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3216 - accuracy: 0.7200
Epoch 92/200
804/804 [==============================] - 1s 2ms/step - loss: 1.3198 - accuracy: 0.7226
Epoch 93/200
804/804 [==============================] - 2s 2ms/step - loss: 1.3527 - accuracy: 0.7188
Epoch 94/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3288 - accuracy: 0.7203
Epoch 95/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3887 - accuracy: 0.7109
Epoch 96/200
804/804 [==============================] - 1s 1ms/step - loss: 1.5975 - accuracy: 0.7031
Epoch 97/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3613 - accuracy: 0.7165
Epoch 98/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3390 - accuracy: 0.7166
Epoch 99/200
804/804 [==============================] - 1s 2ms/step - loss: 1.3389 - accuracy: 0.7176
Epoch 100/200
804/804 [==============================] - 1s 2ms/step - loss: 1.3335 - accuracy: 0.7182
Epoch 101/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3457 - accuracy: 0.7129
Epoch 102/200
804/804 [==============================] - 1s 1ms/step - loss: 1.5487 - accuracy: 0.6978
Epoch 103/200
804/804 [==============================] - 1s 1ms/step - loss: 1.6698 - accuracy: 0.6926
Epoch 104/200
804/804 [==============================] - 1s 1ms/step - loss: 1.9036 - accuracy: 0.6806
Epoch 105/200
804/804 [==============================] - 1s 1ms/step - loss: 1.9494 - accuracy: 0.6787
Epoch 106/200
804/804 [==============================] - 1s 1ms/step - loss: 1.9426 - accuracy: 0.6787
Epoch 107/200
804/804 [==============================] - 1s 1ms/step - loss: 1.4813 - accuracy: 0.7042
Epoch 108/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3085 - accuracy: 0.7112
Epoch 109/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3085 - accuracy: 0.7127
Epoch 110/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3335 - accuracy: 0.7156
Epoch 111/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3366 - accuracy: 0.7162
Epoch 112/200
804/804 [==============================] - 1s 1ms/step - loss: 1.5345 - accuracy: 0.7008
Epoch 113/200
804/804 [==============================] - 1s 2ms/step - loss: 1.3634 - accuracy: 0.7158
Epoch 114/200
804/804 [==============================] - 1s 2ms/step - loss: 1.4484 - accuracy: 0.7095
Epoch 115/200
804/804 [==============================] - 1s 2ms/step - loss: 1.6262 - accuracy: 0.6979
Epoch 116/200
804/804 [==============================] - 1s 1ms/step - loss: 1.4953 - accuracy: 0.7043
Epoch 117/200
804/804 [==============================] - 1s 1ms/step - loss: 1.4547 - accuracy: 0.7069
Epoch 118/200
804/804 [==============================] - 1s 1ms/step - loss: 1.4996 - accuracy: 0.7021
Epoch 119/200
804/804 [==============================] - 1s 2ms/step - loss: 1.6917 - accuracy: 0.6850
Epoch 120/200
804/804 [==============================] - 2s 2ms/step - loss: 1.4605 - accuracy: 0.7021
Epoch 121/200
804/804 [==============================] - 1s 2ms/step - loss: 1.4675 - accuracy: 0.6991
Epoch 122/200
804/804 [==============================] - 1s 2ms/step - loss: 1.4123 - accuracy: 0.7051
Epoch 123/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3322 - accuracy: 0.7111
Epoch 124/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3499 - accuracy: 0.7100
Epoch 125/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3335 - accuracy: 0.7056
Epoch 126/200
804/804 [==============================] - 1s 2ms/step - loss: 1.3630 - accuracy: 0.7023
Epoch 127/200
804/804 [==============================] - 1s 2ms/step - loss: 1.3308 - accuracy: 0.7100
Epoch 128/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3225 - accuracy: 0.7104
Epoch 129/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3056 - accuracy: 0.7091
Epoch 130/200
804/804 [==============================] - 1s 1ms/step - loss: 1.2418 - accuracy: 0.7093
Epoch 131/200
804/804 [==============================] - 1s 2ms/step - loss: 1.2531 - accuracy: 0.7054
Epoch 132/200
804/804 [==============================] - 1s 1ms/step - loss: 1.2229 - accuracy: 0.7117
Epoch 133/200
804/804 [==============================] - 1s 1ms/step - loss: 1.2290 - accuracy: 0.7088
Epoch 134/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1459 - accuracy: 0.7140
Epoch 135/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1200 - accuracy: 0.7164
Epoch 136/200
804/804 [==============================] - 1s 2ms/step - loss: 1.1175 - accuracy: 0.7160
Epoch 137/200
804/804 [==============================] - 1s 2ms/step - loss: 1.1926 - accuracy: 0.7088
Epoch 138/200
804/804 [==============================] - 1s 2ms/step - loss: 1.1486 - accuracy: 0.7117
Epoch 139/200
804/804 [==============================] - 1s 2ms/step - loss: 1.1174 - accuracy: 0.7140
Epoch 140/200
804/804 [==============================] - 1s 2ms/step - loss: 1.1094 - accuracy: 0.7168
Epoch 141/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1110 - accuracy: 0.7177
Epoch 142/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1140 - accuracy: 0.7177
Epoch 143/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1106 - accuracy: 0.7159
Epoch 144/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1230 - accuracy: 0.7115
Epoch 145/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3357 - accuracy: 0.7078
Epoch 146/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1489 - accuracy: 0.7175
Epoch 147/200
804/804 [==============================] - 1s 1ms/step - loss: 0.9660 - accuracy: 0.7264
Epoch 148/200
804/804 [==============================] - 1s 2ms/step - loss: 0.9538 - accuracy: 0.7290
Epoch 149/200
804/804 [==============================] - 1s 1ms/step - loss: 0.9561 - accuracy: 0.7297
Epoch 150/200
804/804 [==============================] - 1s 1ms/step - loss: 1.0675 - accuracy: 0.7229
Epoch 151/200
804/804 [==============================] - 1s 1ms/step - loss: 1.0702 - accuracy: 0.7226
Epoch 152/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1062 - accuracy: 0.7190
Epoch 153/200
804/804 [==============================] - 1s 2ms/step - loss: 1.1263 - accuracy: 0.7169
Epoch 154/200
804/804 [==============================] - 1s 2ms/step - loss: 1.4361 - accuracy: 0.7012
Epoch 155/200
804/804 [==============================] - 1s 1ms/step - loss: 1.6583 - accuracy: 0.6856
Epoch 156/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1514 - accuracy: 0.7158
Epoch 157/200
804/804 [==============================] - 1s 1ms/step - loss: 1.2140 - accuracy: 0.7149
Epoch 158/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1159 - accuracy: 0.7192
Epoch 159/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1799 - accuracy: 0.7173
Epoch 160/200

804/804 [==============================] - 1s 1ms/step - loss: 1.5367 - accuracy: 0.6976
Epoch 161/200
804/804 [==============================] - 1s 1ms/step - loss: 1.4996 - accuracy: 0.7054
Epoch 162/200
804/804 [==============================] - 1s 1ms/step - loss: 1.4939 - accuracy: 0.7037
Epoch 163/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3787 - accuracy: 0.7044
Epoch 164/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1355 - accuracy: 0.7181
Epoch 165/200
804/804 [==============================] - 1s 1ms/step - loss: 1.5654 - accuracy: 0.6990
Epoch 166/200
804/804 [==============================] - 1s 1ms/step - loss: 1.5449 - accuracy: 0.6967
Epoch 167/200
804/804 [==============================] - 1s 2ms/step - loss: 1.5189 - accuracy: 0.6998
Epoch 168/200
804/804 [==============================] - 1s 2ms/step - loss: 1.5012 - accuracy: 0.7003
Epoch 169/200
804/804 [==============================] - 1s 1ms/step - loss: 1.3510 - accuracy: 0.7075
Epoch 170/200
804/804 [==============================] - 1s 1ms/step - loss: 1.5045 - accuracy: 0.6988
Epoch 171/200
804/804 [==============================] - 1s 1ms/step - loss: 1.2528 - accuracy: 0.7124
Epoch 172/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1257 - accuracy: 0.7197
Epoch 173/200
804/804 [==============================] - 1s 1ms/step - loss: 1.2245 - accuracy: 0.7164
Epoch 174/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1500 - accuracy: 0.7180
Epoch 175/200
804/804 [==============================] - 1s 1ms/step - loss: 1.0991 - accuracy: 0.7199
Epoch 176/200
804/804 [==============================] - 1s 2ms/step - loss: 1.1783 - accuracy: 0.7116
Epoch 177/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1401 - accuracy: 0.7151
Epoch 178/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1085 - accuracy: 0.7175
Epoch 179/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1351 - accuracy: 0.7133
Epoch 180/200
804/804 [==============================] - 1s 2ms/step - loss: 1.1152 - accuracy: 0.7096
Epoch 181/200
804/804 [==============================] - 1s 2ms/step - loss: 1.1198 - accuracy: 0.7143
Epoch 182/200
804/804 [==============================] - 1s 2ms/step - loss: 1.0048 - accuracy: 0.7254
Epoch 183/200
804/804 [==============================] - 1s 1ms/step - loss: 1.0380 - accuracy: 0.7226
Epoch 184/200
804/804 [==============================] - 1s 1ms/step - loss: 1.0127 - accuracy: 0.7195
Epoch 185/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1581 - accuracy: 0.7169
Epoch 186/200
804/804 [==============================] - 1s 1ms/step - loss: 1.0714 - accuracy: 0.7229
Epoch 187/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1567 - accuracy: 0.7167
Epoch 188/200
804/804 [==============================] - 1s 1ms/step - loss: 1.0319 - accuracy: 0.7235
Epoch 189/200
804/804 [==============================] - 1s 1ms/step - loss: 1.0754 - accuracy: 0.7229
Epoch 190/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1309 - accuracy: 0.7185
Epoch 191/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1270 - accuracy: 0.7139
Epoch 192/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1184 - accuracy: 0.7199
Epoch 193/200
804/804 [==============================] - 1s 2ms/step - loss: 1.0966 - accuracy: 0.7252
Epoch 194/200
804/804 [==============================] - 2s 2ms/step - loss: 1.0742 - accuracy: 0.7276
Epoch 195/200
804/804 [==============================] - 1s 2ms/step - loss: 1.0699 - accuracy: 0.7280
Epoch 196/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1117 - accuracy: 0.7252
Epoch 197/200
804/804 [==============================] - 1s 2ms/step - loss: 1.1096 - accuracy: 0.7226
Epoch 198/200
804/804 [==============================] - 1s 1ms/step - loss: 1.1802 - accuracy: 0.7130
Epoch 199/200
804/804 [==============================] - 1s 2ms/step - loss: 1.2310 - accuracy: 0.7118
Epoch 200/200
804/804 [==============================] - 1s 1ms/step - loss: 1.0937 - accuracy: 0.7236

#### Alternative Model 2

In [73]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [74]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 10

In [75]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = number_input_features * 3

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

348

In [76]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [77]:
# First hidden layer
nn_A2.add(
    Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation="relu")
)


# Output layer
nn_A2.add(Dense(units=units=number_output_neurons_A2, activation="linear"))


# Check the structure of the model
nn_A2.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_7 (Dense)             (None, 348)               40716

 dense_8 (Dense)             (None, 1)                 349

=================================================================
Total params: 41,065
Trainable params: 41,065
Non-trainable params: 0
_________________________________________________________________

In [78]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [79]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train , epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 1ms/step - loss: 2.0642 - accuracy: 0.6621
Epoch 2/50
804/804 [==============================] - 1s 1ms/step - loss: 2.4192 - accuracy: 0.6669
Epoch 3/50
804/804 [==============================] - 1s 1ms/step - loss: 2.8112 - accuracy: 0.6327
Epoch 4/50
804/804 [==============================] - 1s 1ms/step - loss: 3.0539 - accuracy: 0.6232
Epoch 5/50
804/804 [==============================] - 1s 1ms/step - loss: 4.4577 - accuracy: 0.5867
Epoch 6/50
804/804 [==============================] - 1s 1ms/step - loss: 4.2285 - accuracy: 0.5914
Epoch 7/50
804/804 [==============================] - 1s 1ms/step - loss: 5.3353 - accuracy: 0.5477
Epoch 8/50
804/804 [==============================] - 1s 1ms/step - loss: 5.4834 - accuracy: 0.5348
Epoch 9/50
804/804 [==============================] - 1s 1ms/step - loss: 3.6630 - accuracy: 0.6018
Epoch 10/50
804/804 [==============================] - 1s 1ms/step - loss: 3.1902 - accuracy: 0.6528
Epoch 11/50
804/804 [==============================] - 1s 1ms/step - loss: 3.1500 - accuracy: 0.6542
Epoch 12/50
804/804 [==============================] - 1s 1ms/step - loss: 3.2040 - accuracy: 0.6300
Epoch 13/50
804/804 [==============================] - 1s 1ms/step - loss: 2.0615 - accuracy: 0.6909
Epoch 14/50
804/804 [==============================] - 1s 1ms/step - loss: 1.7408 - accuracy: 0.7006
Epoch 15/50
804/804 [==============================] - 1s 1ms/step - loss: 1.7483 - accuracy: 0.6950
Epoch 16/50
804/804 [==============================] - 1s 1ms/step - loss: 1.7485 - accuracy: 0.6871
Epoch 17/50
804/804 [==============================] - 1s 1ms/step - loss: 1.6547 - accuracy: 0.7096
Epoch 18/50
804/804 [==============================] - 1s 1ms/step - loss: 1.6963 - accuracy: 0.7079
Epoch 19/50
804/804 [==============================] - 1s 1ms/step - loss: 1.7060 - accuracy: 0.7055
Epoch 20/50
804/804 [==============================] - 1s 1ms/step - loss: 1.6095 - accuracy: 0.7047
Epoch 21/50
804/804 [==============================] - 1s 1ms/step - loss: 1.4125 - accuracy: 0.7047
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 1.2700 - accuracy: 0.7167
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 1.2925 - accuracy: 0.7137
Epoch 24/50
804/804 [==============================] - 1s 1ms/step - loss: 1.2946 - accuracy: 0.7124
Epoch 25/50
804/804 [==============================] - 1s 1ms/step - loss: 1.2497 - accuracy: 0.7206
Epoch 26/50
804/804 [==============================] - 1s 1ms/step - loss: 1.2244 - accuracy: 0.7227
Epoch 27/50
804/804 [==============================] - 1s 1ms/step - loss: 1.2860 - accuracy: 0.7183
Epoch 28/50
804/804 [==============================] - 1s 1ms/step - loss: 1.3663 - accuracy: 0.7066
Epoch 29/50
804/804 [==============================] - 1s 1ms/step - loss: 1.2394 - accuracy: 0.7142
Epoch 30/50
804/804 [==============================] - 1s 1ms/step - loss: 1.4136 - accuracy: 0.6932
Epoch 31/50
804/804 [==============================] - 1s 1ms/step - loss: 1.7905 - accuracy: 0.6779
Epoch 32/50
804/804 [==============================] - 1s 1ms/step - loss: 1.9407 - accuracy: 0.6760
Epoch 33/50
804/804 [==============================] - 1s 1ms/step - loss: 1.4291 - accuracy: 0.7048
Epoch 34/50
804/804 [==============================] - 1s 1ms/step - loss: 1.3143 - accuracy: 0.7072
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 1.2866 - accuracy: 0.7122
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 1.7789 - accuracy: 0.6766
Epoch 37/50
804/804 [==============================] - 1s 1ms/step - loss: 1.3870 - accuracy: 0.7027
Epoch 38/50
804/804 [==============================] - 1s 1ms/step - loss: 1.2168 - accuracy: 0.7205
Epoch 39/50
804/804 [==============================] - 1s 1ms/step - loss: 1.4451 - accuracy: 0.7044
Epoch 40/50
804/804 [==============================] - 1s 1ms/step - loss: 1.6545 - accuracy: 0.6920
Epoch 41/50
804/804 [==============================] - 1s 1ms/step - loss: 1.5362 - accuracy: 0.6984
Epoch 42/50
804/804 [==============================] - 1s 1ms/step - loss: 1.5139 - accuracy: 0.7018
Epoch 43/50
804/804 [==============================] - 1s 1ms/step - loss: 1.4947 - accuracy: 0.7111
Epoch 44/50
804/804 [==============================] - 1s 1ms/step - loss: 1.3576 - accuracy: 0.7170
Epoch 45/50
804/804 [==============================] - 1s 1ms/step - loss: 1.3890 - accuracy: 0.7143
Epoch 46/50
804/804 [==============================] - 1s 1ms/step - loss: 1.4674 - accuracy: 0.7156
Epoch 47/50
804/804 [==============================] - 1s 1ms/step - loss: 1.3871 - accuracy: 0.7218
Epoch 48/50
804/804 [==============================] - 1s 1ms/step - loss: 1.3600 - accuracy: 0.7121
Epoch 49/50
804/804 [==============================] - 1s 1ms/step - loss: 1.2255 - accuracy: 0.7207
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 1.1959 - accuracy: 0.7147

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [80]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.7650 - accuracy: 0.7254 - 242ms/epoch - 902us/step
Loss: 0.7649664878845215, Accuracy: 0.7253644466400146

In [81]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 1.0611 - accuracy: 0.7242 - 245ms/epoch - 914us/step
Loss: 1.0611239671707153, Accuracy: 0.7241982221603394

In [82]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 1.3914 - accuracy: 0.7002 - 363ms/epoch - 1ms/step
Loss: 1.3914456367492676, Accuracy: 0.7001749277114868

### Step 3: Save each of your alternative models as an HDF5 file.

In [83]:
# Set the file path for the first alternative model
file_path = Path("./Resources/AlphabetSoup_A1.h5")

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [84]:
# Set the file path for the second alternative model
file_path = Path("./Resources/AlphabetSoup_A2.h5")

# Export your model to a HDF5 file
nn_A2.save(file_path)